language: rust
rust:
- stable

env:
  global:
  # This will be part of the release tarball
  - PROJECT_NAME=catsay
  - MAKE_DEB=yes
  - DEB_MAINTAINER="Jim Verheijde <jim.verheijde@hotmail.com>"
  - DEB_DESCRIPTION="catsay, written in Rust"

matrix:
  include:
    # ARM 64 bit
  - os: linux
    env: TARGET=aarch64-unknown-linux-gnu
    # need Trusty because the glibc in Precise is too old and doesn't support 64-bit arm
    dist: trusty
    sudo: required
    # Extra packages only for this job
    addons:
      apt:
        packages: &aarch64_unknown_linux_gnu
        # Transparent emulation
        - qemu-user-static
        - binfmt-support
  # OSX 32 bit
  - os: osx
    env: TARGET=i686-apple-darwin
  - os: linux
    env: TARGET=i686-unknown-linux-gnu
    addons:
      apt:
        packages: &i686_unknown_linux_gnu
        # Cross compiler and cross compiled C libraries
        - gcc-multilib
  # OSX 64 bit
  - os: osx
    env: TARGET=x86_64-apple-darwin
  # Linux 32 bit
  - os: linux
    env: TARGET=i686-unknown-linux-gnu
    addons:
      apt:
        packages: &i686_unknown_linux_gnu
        # Cross compiler and cross compiled C libraries
        - gcc-multilib
  # Linux 64 bit
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu

before_install:
- export PATH="$PATH:$HOME/.cargo/bin"

install:
- bash ci/install.sh

script:
- bash ci/script.sh

before_deploy:
- bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: OkrYD4oafM2yYTRtevipngu42yb5CrfMI7/bKYO6XVdMgvywOzVVhSpT4c30H8rEmYlcZOaXS6HCUU4PwEmnLhAq0xYGfBnjQSDZ89lt8UezAIqSRLGuvrr94bMmFpnoH4hzEsu6+bzQqwN4bQncm4I9zXnHHOrcy+h7Z8H/xWR3gWk9K2FOMiblGQ+jXY6jjHtVceks6RP1Ke6K73vPsF/TtcuOFB/VY0O4gwIZuDZuBvwqR34b+IeXv0aVfnqPndk6nNjg+zZUTDHwF4pHMBJVGUEgzSlE9KumSebBi7f8rEPUl9X4y5NChKbeqNF9cFVb3qwTHa8+ghrvUL0Ylm2toOiwwMLV7slE3XxXOzWQ1Bnn7cWLiuBTSjVxCcveRHcWH0P5ZiNamvXXF5+VTrhj0g1CIu09geGPyFCYPaSYa/OGNGMntlBTpFAgW+mLf4HnN/Oaf/g2yDv91SsC4eQk16Mm7dCNNYStQT/CkiJZ21yMJjkgqnmrnvz/jgEVfUGlsugqhX7jZX40rZMQvyYaP+mqLlyZnO7SEocr3FKZZsEcwFDf4d9anPahBNQUOzUVzuHaqnY3v6bZQ7SdDcx7HoA+wnvs/fvaScF4ZiBzgzd35xU50f6gdD3z0FlCu5erEgOp3cdy6+rkN55CxkxERlIOz2zGjW+NkI1oYZM=
  file: "${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*"
  skip_cleanup: true
  on:
    tags: true
  branches:
    only:
    # Pushes and PR to the master branch
    - master