name: cat-say
version: git
summary: Useless cli tool of a cat repeating what you say
description: |
  catsay is a cli tool of a cat repeating what you say, it is written in Rust

confinement: strict

parts:
  catsay:
    source: .
    plugin: rust
    build-attributes: [no-system-libraries]

apps:
  cat-say:
    command: cat-say